<a href="https://colab.research.google.com/github/stephanyresque/Ciencia-de-dados-2/blob/main/23_09_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


In [1]:
import numpy as np

In [3]:
#Arrays em Numpy -> estrutura básica
#devem ser do mesmo tipo -> vetor

a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#array é diferente de lista!

lista = [1,'a', 4.5, 'aaa']
print(lista)

[1, 'a', 4.5, 'aaa']


In [5]:
for elemento in lista:
  print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'str'>


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a = np.array(lista)
print(a) #converteu tudo pra string -> sempre fará isso se tivermos dados de diferentes tipos no array

['1' 'a' '4.5' 'aaa']


In [8]:
for elemento in a:
  print(type(elemento))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [9]:
print(a.dtype) #dtype -> data type

<U32


## Operações matemáticas

In [11]:
lista = [1,2,3,4,5]
# nova_lista = lista + 1
# print(nova_lista) -> dá erro

In [12]:
#podemos fazer isso com numpy!

a = np.array(lista)
novo_array = a + 1 #isso adicionará 1 a todos os elementos
print(novo_array)

[2 3 4 5 6]


In [13]:
novo_array = a * 10
print(novo_array)

[10 20 30 40 50]


In [14]:
novo_array = a **2
print(novo_array)

[ 1  4  9 16 25]


In [16]:

a = np.array(range(1,10_000_001))
soma = np.sum(a)
print(soma)

50000005000000


## Arrays

In [17]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [18]:
#indexação e slice

print(a[0])

1


In [19]:
print(a[1:4])

[2 3 4]


In [20]:
print(a[0:-1])

[1 2 3 4]


In [21]:
print(a[0:-1:2])

[1 3]


In [22]:
print(a[0::2])

[1 3 5]


In [23]:
print(a[::2])

[1 3 5]


In [24]:
print(a[::])

[1 2 3 4 5]


In [25]:
print(a[::-1])

[5 4 3 2 1]


## funções básicas

In [26]:
precos = np.array([10, 13, 15, 30, 45, 50])

#atualizar valores!
precos = precos * 1.1
print(precos)

[11.  14.3 16.5 33.  49.5 55. ]


In [27]:
#saber uma soma
vendas = np.array([300, 120, 380, 50, 15, 8])
total_vendas = np.sum(vendas)
print(total_vendas)

873


In [28]:
media_vendas = np.mean(vendas)
print(media_vendas)

145.5


In [29]:
#máximos e mínimos
print(np.max(vendas))
print(np.min(vendas))

380
8


In [31]:
#a função sort serve para ordenar elementos
vendas_ordenadas = np.sort(vendas)
print(vendas_ordenadas)


[  8  15  50 120 300 380]


In [32]:
#a função dot serve para calcular o produto escalar de dois arrays

quantidade = np.array([30, 50, 10, 20, 10, 5])
total = np.dot(precos, quantidade)
print(total)

2640.0


In [33]:
print(quantidade * precos)

[330. 715. 165. 660. 495. 275.]


In [34]:
print(np.sum(quantidade * precos))


2640.0


## exercícios

In [36]:
#exe1

dados = [127, 90, 201, 150, 210, 220, 115]

media_vendas = np.mean(dados)
print(f"Média de vendas: R${media_vendas:.2f}")

Média de vendas: R$159.00


In [37]:
#exe 2

precos = np.array([31.40, 31.25, 30.95, 31.20, 31.60, 31.50])

preco_max = np.max(precos)
preco_min = np.min(precos)
print(f"Preço máximo: R${preco_max:.2f}")
print(f"Preço mínimo: R${preco_min:.2f}")

Preço máximo: R$31.60
Preço mínimo: R$30.95


In [38]:
#variação

variancia = np.var(precos)
print(f"Variação: R${variancia:.2f}")


Variação: R$0.05


In [39]:
#exe 2

quantidades = np.array([5, 3, 2])
precos = np.array([100, 200, 50])

total = np.dot(quantidades, precos)
print(f"Total: R${total:.2f}")

Total: R$1200.00
