<a href="https://colab.research.google.com/github/stephanyresque/Ciencia-de-dados-2/blob/main/23_09_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


In [1]:
import numpy as np

In [3]:
#Arrays em Numpy -> estrutura básica
#devem ser do mesmo tipo -> vetor

a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#array é diferente de lista!

lista = [1,'a', 4.5, 'aaa']
print(lista)

[1, 'a', 4.5, 'aaa']


In [5]:
for elemento in lista:
  print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'str'>


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a = np.array(lista)
print(a) #converteu tudo pra string -> sempre fará isso se tivermos dados de diferentes tipos no array

['1' 'a' '4.5' 'aaa']


In [8]:
for elemento in a:
  print(type(elemento))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [9]:
print(a.dtype) #dtype -> data type

<U32


## Operações matemáticas

In [11]:
lista = [1,2,3,4,5]
# nova_lista = lista + 1
# print(nova_lista) -> dá erro

In [12]:
#podemos fazer isso com numpy!

a = np.array(lista)
novo_array = a + 1 #isso adicionará 1 a todos os elementos
print(novo_array)

[2 3 4 5 6]


In [13]:
novo_array = a * 10
print(novo_array)

[10 20 30 40 50]


In [14]:
novo_array = a **2
print(novo_array)

[ 1  4  9 16 25]


In [16]:

a = np.array(range(1,10_000_001))
soma = np.sum(a)
print(soma)

50000005000000


## Arrays

In [17]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [18]:
#indexação e slice

print(a[0])

1


In [19]:
print(a[1:4])

[2 3 4]


In [20]:
print(a[0:-1])

[1 2 3 4]


In [21]:
print(a[0:-1:2])

[1 3]


In [22]:
print(a[0::2])

[1 3 5]


In [23]:
print(a[::2])

[1 3 5]


In [24]:
print(a[::])

[1 2 3 4 5]


In [25]:
print(a[::-1])

[5 4 3 2 1]
