<a href="https://colab.research.google.com/github/stephanyresque/Ciencia-de-dados-2/blob/main/26_09_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Munpy pt 2

## exercícios

In [1]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo)

In [2]:
media

5.8

In [4]:
desvio_padrao = np.std(tempos_ciclo)
print(desvio_padrao)

0.592546294487706


In [9]:
posicoes = np.where((tempos_ciclo > media  + 2*desvio_padrao) | (tempos_ciclo < media - 2*desvio_padrao))

In [10]:
print(tempos_ciclo[posicoes])

[7.2]


In [13]:
posicoes = np.where((tempos_ciclo <= media  + 2*desvio_padrao) & (tempos_ciclo >= media - 2*desvio_padrao))
print(tempos_ciclo[posicoes])

[5.5 5.7 5.9 6.  5.8 5.6 5.7 4.8]


In [14]:
#bônus

rng = np.random.default_rng(seed = 0)
tempos = rng.normal(loc = media, scale = desvio_padrao, size = 100)
print(tempos)

[5.87450098 5.72172175 6.17948007 5.86215818 5.4825911  6.01426181
 6.57268039 6.36118932 5.38300429 5.0501792  5.43068103 5.82448756
 4.42231163 5.67035581 5.06174008 5.36609769 5.47750136 5.61257751
 6.04391015 6.41773743 5.72383726 6.60969287 5.40584136 6.00828599
 6.33534791 5.85570664 5.35944227 5.25383504 5.52877626 5.9304758
 5.20175449 5.67605379 5.70565181 6.12047605 5.92719547 6.01057478
 5.41257628 5.72319792 6.26454176 6.68492709 5.05394538 6.69706992
 6.5974935  6.26296318 5.9567022  5.6139862  6.66394475 6.9615438
 6.86755207 6.57925986 6.01176444 5.08401527 5.79736072 6.18899179
 5.03658619 6.03412811 6.05471414 6.21243754 5.09835529 5.40791059
 5.54139191 5.10683821 6.83065599 5.50614994 5.99492973 5.6467838
 6.73828099 6.58237501 6.17529075 4.49431839 5.83082958 6.20511572
 6.39489371 5.43386147 6.87962608 5.01758352 5.40801402 6.35406041
 5.82906713 6.98651031 5.91170635 5.42480319 5.57627614 5.15344541
 5.04291535 6.17354799 6.14436765 6.56708603 5.35286113 6.8008743

## Reshape

In [15]:
#para mudar o formato do nosso array

vendas = np.array([200, 220, 250, 300, 280, 350, 123, 555,788,234, 654, 344, 125, 356])

#reorganizar os dados em uma matriz 2x7?

vendas_re = np.reshape(vendas, (2, 7))
print(vendas_re)

[[200 220 250 300 280 350 123]
 [555 788 234 654 344 125 356]]


In [16]:
print(vendas)

[200 220 250 300 280 350 123 555 788 234 654 344 125 356]


In [17]:
print(vendas.ndim) #me retorna a dimensão

1


In [18]:
print(vendas.shape)

(14,)


In [19]:
print(vendas_re.ndim)

2


In [20]:
print(vendas_re.shape)

(2, 7)


In [21]:
vendas_re[0]

array([200, 220, 250, 300, 280, 350, 123])

In [22]:
vendas_re[1]

array([555, 788, 234, 654, 344, 125, 356])

In [23]:
vendas_re[0][3]

300

In [24]:
vendas_re[1][-1]

356

In [26]:
vendas_re.sum(), np.sum(vendas_re)

(4779, 4779)

In [28]:
#axis = eixo

np.sum(vendas_re, axis=0) #soma das colunas ->ao longo do eixo 0

array([ 755, 1008,  484,  954,  624,  475,  479])

In [29]:
np.sum(vendas_re, axis=1) #ao longo do eixo 1

array([1723, 3056])

## Exemplos de reshape

In [31]:
vendas = np.array([200, 220, 250, 300, 280, 350, 123, 555,788,234, 654, 344, 125, 356])

vendas_re = np.reshape(vendas, (2,-1)) #com -1 o numpy faz o calculo para decidir a outra dimensão válida
print(vendas_re)

[[200 220 250 300 280 350 123]
 [555 788 234 654 344 125 356]]


In [32]:
vendas_re = np.reshape(vendas, (-1,7))
print(vendas_re)

[[200 220 250 300 280 350 123]
 [555 788 234 654 344 125 356]]


In [34]:
rng = np.random.default_rng(seed = 42)

vendas = rng.integers(low=20, high=200, size=30, endpoint=True)
print(vendas)

[ 36 160 138  99  98 175  35 146  56  37 115 196 153 157 149 162 112  43
 171 101 110  87  53 187 161 136  92 168 118 100]


In [36]:
vendas_semana = np.reshape(vendas, (-1, 6))
print(vendas_semana)

[[ 36 160 138  99  98 175]
 [ 35 146  56  37 115 196]
 [153 157 149 162 112  43]
 [171 101 110  87  53 187]
 [161 136  92 168 118 100]]


In [37]:
#outra forma
vendas = rng.integers(low=20, high=200, size=(5,6), endpoint=True)
print(vendas)

[[101  61  36 120 180  31]
 [175 169  70 134  49 157]
 [146  84  32 195 100 181]
 [142 160 157  55  85 104]
 [110  27 118  47 154 143]]


In [38]:
total_vendas_semana = np.sum(vendas_semana, axis=1)
print(total_vendas_semana)

[706 585 776 709 775]


In [39]:
media_vendas_semana = np.mean(vendas_semana, axis=1)
print(media_vendas_semana)

[117.66666667  97.5        129.33333333 118.16666667 129.16666667]


In [40]:
media_vendas_dia = np.mean(vendas_semana, axis=0)
print(media_vendas_dia)

[111.2 140.  109.  110.6  99.2 140.2]


## Exercícios

In [41]:
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])


In [42]:
total_venda_produto = np.sum(vendas, axis = 1)
print(total_venda_produto)

[325 433 368]


In [44]:
print(f"Vendas do produto A: {total_venda_produto[0]}")
print(f"Vendas do produto B: {total_venda_produto[1]}")
print(f"Vendas do produto C: {total_venda_produto[2]}")

Vendas do produto A: 325
Vendas do produto B: 433
Vendas do produto C: 368


In [43]:
total_venda_dia = np.sum(vendas, axis = 0)
print(total_venda_dia)

[207 225 216 234 244]


In [45]:
for i in range(len(total_venda_dia)):
  print(f"Total vendas dia {i+1}: {total_venda_dia[i]}")

Total vendas dia 1: 207
Total vendas dia 2: 225
Total vendas dia 3: 216
Total vendas dia 4: 234
Total vendas dia 5: 244


In [46]:
# considere os seguintes dados aleatórios como início
rng = np.random.default_rng(seed=42)
respostas = rng.integers(low=0, high=10, size=210, endpoint=True)
print(respostas)

[ 0  8  7  4  4  9  0  7  2  1  5 10  8  8  7  8  5  1  9  4  5  4  2 10
  8  7  4  9  5  4  4  2  1  6  9  0  9  9  3  6  1  8  7  3  0 10  4  9
  7  8  8  2  4  5  5  0  6  1  8  7 10  8  4 10  4  3  9  4  0  5  8  2
  5  1  7  5  3  2  6  7 10  4  1  9  6  7  1  3  8  9  4  8  9  4  9  3
  2  7  7  1  9  2  8  0  8  8  8  7  5  7  3  8  6  5  5  6  0  1  2  1
  4  7  7  5  9  6  0  8  6  6  6  6  0  6  8  3  6  0  3  4 10  2  3  4
 10  9  0  2  9  0  9  3 10  3  4  7  1  6  5  8 10  7  4  4  4  8  3  1
  3  0  1  0  8  7  7  5  7  1  9  5 10  1  5  7  5  4  1  4  2  3  7  6
  6  3 10  0  3  1  3 10  4  9  5  7  5  2  8 10  2  8]


In [49]:
respostas_organizadas = np.reshape(respostas, (7,30))
print(respostas_organizadas)

[[ 0  8  7  4  4  9  0  7  2  1  5 10  8  8  7  8  5  1  9  4  5  4  2 10
   8  7  4  9  5  4]
 [ 4  2  1  6  9  0  9  9  3  6  1  8  7  3  0 10  4  9  7  8  8  2  4  5
   5  0  6  1  8  7]
 [10  8  4 10  4  3  9  4  0  5  8  2  5  1  7  5  3  2  6  7 10  4  1  9
   6  7  1  3  8  9]
 [ 4  8  9  4  9  3  2  7  7  1  9  2  8  0  8  8  8  7  5  7  3  8  6  5
   5  6  0  1  2  1]
 [ 4  7  7  5  9  6  0  8  6  6  6  6  0  6  8  3  6  0  3  4 10  2  3  4
  10  9  0  2  9  0]
 [ 9  3 10  3  4  7  1  6  5  8 10  7  4  4  4  8  3  1  3  0  1  0  8  7
   7  5  7  1  9  5]
 [10  1  5  7  5  4  1  4  2  3  7  6  6  3 10  0  3  1  3 10  4  9  5  7
   5  2  8 10  2  8]]


In [52]:
for i in range(7):
  print(f"Respostas dia {i+1}: {respostas_organizadas[i]}")

Respostas dia 1: [ 0  8  7  4  4  9  0  7  2  1  5 10  8  8  7  8  5  1  9  4  5  4  2 10
  8  7  4  9  5  4]
Respostas dia 2: [ 4  2  1  6  9  0  9  9  3  6  1  8  7  3  0 10  4  9  7  8  8  2  4  5
  5  0  6  1  8  7]
Respostas dia 3: [10  8  4 10  4  3  9  4  0  5  8  2  5  1  7  5  3  2  6  7 10  4  1  9
  6  7  1  3  8  9]
Respostas dia 4: [4 8 9 4 9 3 2 7 7 1 9 2 8 0 8 8 8 7 5 7 3 8 6 5 5 6 0 1 2 1]
Respostas dia 5: [ 4  7  7  5  9  6  0  8  6  6  6  6  0  6  8  3  6  0  3  4 10  2  3  4
 10  9  0  2  9  0]
Respostas dia 6: [ 9  3 10  3  4  7  1  6  5  8 10  7  4  4  4  8  3  1  3  0  1  0  8  7
  7  5  7  1  9  5]
Respostas dia 7: [10  1  5  7  5  4  1  4  2  3  7  6  6  3 10  0  3  1  3 10  4  9  5  7
  5  2  8 10  2  8]


In [53]:
media_satisfacao_dia = np.mean(respostas_organizadas, axis=1)
print(media_satisfacao_dia)

[5.5        5.06666667 5.36666667 5.1        4.96666667 5.
 5.03333333]


In [54]:
media_geral = np.mean(respostas)
print(media_geral)

5.147619047619048
