<a href="https://colab.research.google.com/github/stephanyresque/Ciencia-de-dados-2/blob/main/redes_neurais_pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.0+cu121


In [3]:
# Criando um tensor 2x2
tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Tensor:\n", tensor)

Tensor:
 tensor([[1., 2.],
        [3., 4.]])


In [4]:
# Somando 10 a cada elemento do tensor
tensor_add = tensor + 10
print("Tensor após adição:\n", tensor_add)

Tensor após adição:
 tensor([[11., 12.],
        [13., 14.]])


In [5]:
# Verificar se há GPU disponível
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Dispositivo disponível para PyTorch:", device)

# Mover o tensor para GPU (se disponível)
tensor = tensor.to(device)

Dispositivo disponível para PyTorch: cuda


In [6]:
# Criar um tensor 3x3 com valores aleatórios
random_tensor = torch.rand(3, 3)
print("Tensor Aleatório:\n", random_tensor)

Tensor Aleatório:
 tensor([[0.2335, 0.5822, 0.7357],
        [0.3779, 0.2542, 0.6975],
        [0.2300, 0.0719, 0.6850]])


In [7]:
# Soma, Subtração e Multiplicação
tensor_a = torch.tensor([1.0, 2.0, 3.0])
tensor_b = torch.tensor([4.0, 5.0, 6.0])

soma = tensor_a + tensor_b
produto = tensor_a * tensor_b
print("Soma:", soma)
print("Produto Elemento a Elemento:", produto)

Soma: tensor([5., 7., 9.])
Produto Elemento a Elemento: tensor([ 4., 10., 18.])


In [8]:
from torch import nn

# Criar uma camada com 3 neurônios de entrada e 2 de saída
camada = nn.Linear(3, 2)

# Dados de entrada (1 amostra com 3 características)
entrada = torch.tensor([[1.0, 2.0, 3.0]])

# Passar pela camada linear
saida = camada(entrada)
print("Saída da Camada Linear:", saida)


Saída da Camada Linear: tensor([[-0.2301, -1.0940]], grad_fn=<AddmmBackward0>)


In [9]:
# Criar uma função de ativação ReLU
relu = nn.ReLU()

# Aplicar ReLU na saída da camada
saida_relu = relu(saida)
print("Saída com ReLU aplicada:", saida_relu)


Saída com ReLU aplicada: tensor([[0., 0.]], grad_fn=<ReluBackward0>)


In [11]:
sigmoid = nn.Sigmoid()
saida_sigmoid = sigmoid(saida)
print("Saída com Sigmoid aplicada:", saida_sigmoid)

Saída com Sigmoid aplicada: tensor([[0.4427, 0.2509]], grad_fn=<SigmoidBackward0>)


In [12]:
tanh = nn.Tanh()
saida_tanh = tanh(saida)
print("Saída com Tanh aplicada:", saida_tanh)

Saída com Tanh aplicada: tensor([[-0.2261, -0.7983]], grad_fn=<TanhBackward0>)


In [13]:
class RedeNeural(nn.Module):
    def __init__(self):
        super(RedeNeural, self).__init__()
        # Definir as camadas
        self.camada1 = nn.Linear(3, 4)  # 3 entradas, 4 saídas
        self.camada2 = nn.Linear(4, 1)  # 4 entradas da camada anterior, 1 saída final

    def forward(self, x):
        # Passar os dados pela primeira camada e aplicar ReLU
        x = self.camada1(x)
        x = nn.ReLU()(x)

        # Passar pela segunda camada (sem função de ativação na saída)
        x = self.camada2(x)
        return x

In [14]:
# Criar uma instância da rede
modelo = RedeNeural()

# Dados de entrada (1 amostra com 3 características)
entrada = torch.tensor([[1.0, 2.0, 3.0]])

# Obter a saída da rede
saida_modelo = modelo(entrada)
print("Saída da Rede:", saida_modelo)

Saída da Rede: tensor([[0.2304]], grad_fn=<AddmmBackward0>)


In [15]:
# Definir a função de perda como MSELoss
criterio = nn.MSELoss()

In [16]:
import torch.optim as optim

# Usando o Adam como otimizador, com uma taxa de aprendizado de 0.01
otimizador = optim.Adam(modelo.parameters(), lr=0.01)

In [17]:
# Dados de entrada e saída esperada
entrada = torch.tensor([[1.0, 2.0, 3.0]])  # Exemplo de uma entrada
saida_esperada = torch.tensor([[0.5]])     # Exemplo de uma saída esperada

# Loop de treinamento
for epoca in range(100):  # 100 épocas
    otimizador.zero_grad()     # 1. Zerar gradientes acumulados
    saida = modelo(entrada)    # 2. Forward pass (previsão)
    perda = criterio(saida, saida_esperada)  # 3. Calcular a perda
    perda.backward()           # 4. Retropropagação (calcula gradientes)
    otimizador.step()          # 5. Atualizar os pesos

    # Exibir a perda a cada 10 épocas
    if epoca % 10 == 0:
        print(f"Época {epoca+1}, Perda: {perda.item()}")

Época 1, Perda: 0.07266701757907867
Época 11, Perda: 0.029309136793017387
Época 21, Perda: 0.006975783966481686
Época 31, Perda: 0.00036303431261330843
Época 41, Perda: 0.00020083088020328432
Época 51, Perda: 0.00040021384484134614
Época 61, Perda: 0.00013371820386964828
Época 71, Perda: 3.127274567304994e-06
Época 81, Perda: 8.671479918120895e-06
Época 91, Perda: 7.616245966346469e-06
